// This file will be auto-generated by FlutterFire CLI
// Run: flutterfire configure
//
// For now, this is a placeholder. Follow the Firebase setup instructions.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Firebase configuration for todo-app-1911c
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQqtqrKMdYY8Z1mo7NUgUfl4Vf7c7-JNM',
    appId: '1:218234223961:web:4b4187ab3487c38c462048',
    messagingSenderId: '218234223961',
    projectId: 'todo-app-1911c',
    authDomain: 'todo-app-1911c.firebaseapp.com',
    storageBucket: 'todo-app-1911c.firebasestorage.app',
    measurementId: 'G-1326KP6PRR',
  );

  // Android app - needs to be registered in Firebase Console
  // Run: flutterfire configure to auto-generate this
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQqtqrKMdYY8Z1mo7NUgUfl4Vf7c7-JNM',
    appId: '1:218234223961:web:4b4187ab3487c38c462048',
    messagingSenderId: '218234223961',
    projectId: 'todo-app-1911c',
    storageBucket: 'todo-app-1911c.firebasestorage.app',
  );
}
